variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
#- wrpc_compile
- wrpc_sim
- wrpc_syn

#job_wrpc_compile:
#  stage: wrpc_compile
#  tags:
#   -  modelsim_10_2a 
#  only:
#   - schedules
#  script:
#   - /entrypoint.sh
#   - source ~/setup_modelsim.sh
#   - cd testbench/wrc_core; hdlmake makefile; make clean; make

job_wrpc_sim:
  stage: wrpc_sim
  tags:
  -  modelsim_10.2a 
##  only:
##  - schedules
  script:
   - /entrypoint.sh
   - source ~/setup_modelsim.sh
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_minic
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wrc_core
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_streamers/streamers_multi_test
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_streamers/streamers-only_basic-transfer
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_streamers/streamers-only-fixed-latency
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_streamers/streamers-on-spec_trigger-distribution
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_streamers/streamers-only_multiword-transfer
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/nic_bw_throttling
   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_minic_with_ep
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/xwrf_loopback
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/xwrf_mux
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/top_level
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_endpoint/full_tb
   - cd testbench && make
  artifacts:
    name: WRPC_SIM_CI_$CI_JOB_ID
    paths:
#    - testbench/wrc_core/transcript
#    - testbench/wr_minic/transcript
    - testbench/wr_minic_with_ep/transcript
#    - testbench/wr_streamers/streamers-only_basic-transfer/transcript
#    - testbench/wr_streamers/streamers_multi_test/transcript
    
#job_wrpc_sim_1:
#  stage: wrpc_sim
#  tags:
#  - modelsim_10_2a
#  script:
#   - /entrypoint.sh
#   - source ~/setup_modelsim.sh
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_minic_with_ep
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/top_level
#   - cp /opt/compiled_libs_ise14.7/modelsim.ini testbench/wr_endpoint/full_tb
#   - cd testbench && make
#  artifacts:
#    name: WRPC_SIM_CI_$CI_JOB_ID
#    paths:
#    - testbench/wrc_core/transcript
#    - testbench/wr_minic/transcript
#    - testbench/wr_streamers/streamers-only_basic-transfer/transcript
#    - testbench/wr_streamers/streamers_multi_test/transcript  

job_wrpc_spec:
  stage: wrpc_syn
  tags:
#  - ise_14.7
    - xilinx_ISE_14.7
#  only:
#  - schedules
  script:
  - /entrypoint.sh
  - source ~/setup_ise147.sh
  - source /opt/Xilinx/14.7/ISE_DS/settings64.sh
  - cd syn/spec_ref_design && hdlmake makefile && make
  artifacts:
    name: WRPC_SPEC_CI_$CI_JOB_ID
    paths:
    - syn/spec_ref_design/*.syr
    - syn/spec_ref_design/*.mrp
    - syn/spec_ref_design/*.bit
    - syn/spec_ref_design/*.bin

job_wrpc_svec:
  stage: wrpc_syn
  tags:
#  -  ise_14.7 
    - xilinx_ISE_14.7
#  only:
#  - schedules
  script:
  - /entrypoint.sh
  - source ~/setup_ise147.sh
  - source /opt/Xilinx/14.7/ISE_DS/settings64.sh
  - cd syn/svec_ref_design && hdlmake makefile && make
  artifacts:
    name: WRPC_SVEC_CI_$CI_JOB_ID
    paths:
    - syn/svec_ref_design/*.syr
    - syn/svec_ref_design/*.mrp
    - syn/svec_ref_design/*.bit
    - syn/svec_ref_design/*.bin

job_wrpc_vfchd:
  stage: wrpc_syn
  tags:
#  - quartus_16 
    - altera_quartus_16
#  only:
#  - schedules
  script:
#    - /entrypoint.sh
    - source ~/setup_intel.sh
    - cd syn/vfchd_ref_design
    - hdlmake makefile
    - cat Makefile
    - make
  artifacts:
    name: WRPC_VFCHD_CI_$CI_JOB_ID
    paths:
      - syn/vfchd_ref_design/*.sof
      - syn/vfchd_ref_design/*.rpt
      - syn/vfchd_ref_design/*.rpt
      - syn/vfchd_ref_design/*.summary
      - syn/vfchd_ref_design/*.map.rpt
      - syn/vfchd_ref_design/*.map.summary
      - syn/vfchd_ref_design/*.sta.rpt
      - syn/vfchd_ref_design/*.sta.summary

job_wrpc_pxie_fmc:
  stage: wrpc_syn
  tags:
    - vivado_2018.3 
#  only:
#  - schedules
  script:
    - /entrypoint.sh
    - source ~/setup_vivado.sh
    - source /opt/Xilinx/SDK/2018.3/.settings64-SDK_Core_Tools.sh
    - export LD_LIBRARY_PATH=/opt/Xilinx/Vivado/2018.3/settings64.sh
    - export PATH=/opt/Xilinx/Vivado/2018.3/settings64.sh:$PATH
    - source /opt/Xilinx/Vivado/2018.3/.settings64-Vivado.sh
    - cd syn/pxie_fmc_ref_design
#    # we need to install hdlmake since it doesn't exist in cce's images
#    - pip install hdlmake 
#    - pip install six
#    - locale-gen --purge "en_US.UTF-8" && update-locale LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && export LANG=en_US && export LANGUAGE=en_US && dpkg-reconfigure --frontend noninteractive locales && locale
#    - export LC_CTYPE=en_US.UTF-8
    - hdlmake makefile
    - make files.tcl
    - source /opt/Xilinx/Vivado/2018.3/settings64.sh
    - vivado -mode tcl -source pxie_fmc.tcl
  artifacts:
    name: WRPC_PXIE_CI_$CI_JOB_ID
    paths:
      - syn/pxie_fmc_ref_design/*.rpt
      - syn/pxie_fmc_ref_design/*.dcp
      - syn/pxie_fmc_ref_design/*.bit
